copy_mode: False
nnodes: 1
nproc_per_node: 1
model_name: consistency_test_one
model_type: oai
batch_size: 1
total_training_steps: 100000 
lr: 0.0001
rho: 7.0
final_timesteps: 1280
initial_timesteps: 20
img_channels: 1
base_channels: 64
num_res_blocks: 4
groupnorm: 8
num_heads: 8
num_head_channels: 64
use_scale_shift_norm: False
use_new_attention_order: False
use_conv: False
use_conv_up_down: False
use_flash_attention: True
attention_resolutions: [32,16,8]
dropout: 0.02
image_size: 32
img_dimension: 1
curve: 3.5
emb_time_multiplier: 1
num_time_steps: 20
constant_N: True
root: utils/data/LDCT-and-Projection-data
test_root: utils/data/LDCT-test-data
